apiVersion: v1
kind: Pod
metadata: # Pod명과 라벨(오브젝트 분류를 위함) 지정
  name: web
  labels:
    app: spring-kubernetes
spec: # Pod에서 실행될 컨테이너의 스펙(이미지, CPU, 메모리 등)을 지정
  containers:
    - name: mysql-db # 컨테이너 이름
      image: mysql # 컨테이너가 실행할 이미지 이름
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
            name: docker-hub-secret

    - name: redis-db
      image: redis
      ports:
        - containerPort: 6379
      envFrom:
        - secretRef:
            name: docker-hub-secret

    - name: mongo-db
      image: mongo
      ports:
        - containerPort: 27017
      envFrom:
        - secretRef:
            name: docker-hub-secret

    - name: spring-docker-test
      image: docker.io/eckrin/spring-docker-test
      ports:
        - containerPort: 8080
      envFrom:
        - secretRef:
            name: docker-hub-secret

  imagePullSecrets: # Docker Hub Secret 지정
    - name: docker-hub-secret