apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: spring-kubernetes-service
spec:
  selector:
    app: spring-kubernetes # Pod의 라벨과 일치
  type: NodePort
  ports:
    - port: 80 # 서비스 사용 포트
      targetPort: 8080 # 내부 pod로 연결할 포트
      nodePort: 30001 # 외부에 노출할 포트
      protocol: TCP
      name: http
